# Fabric clocks generated by the Interface Designer PLL.
# The PLL physically generates 60 MHz.  Constrain placement to 80 MHz so the
# deployed design retains routing, voltage and temperature margin.
create_clock -period 14.000 -name pll_60Mhz [get_ports {pll_60Mhz}]
create_clock -period 41.667 -name pll_24Mhz [get_ports {pll_24Mhz}]
# Keep the three HDMI periods harmonic at Efinity STA's 1 ps resolution.
# 13.441/6.720 makes the analyzer eventually align a pixel edge with the
# opposite half-pixel edge and invent a 1 ps setup window in the gearbox.
# 13.440 is only 0.0065% tighter than the physical 74.4 MHz period.
create_clock -period 2.688 -name hdmi_fast_clk [get_ports {hdmi_fast_clk}]
create_clock -period 6.720 -name hdmi_half_pixel_clk [get_ports {hdmi_half_pixel_clk}]
create_clock -period 13.440 -name hdmi_pixel_clk [get_ports {hdmi_pixel_clk}]
create_clock -period 10.417 -name CSI_PCLK [get_ports {CSI_PCLK}]

# Control synchronizers and the dual-clock OSD RAM are the intentional
# crossings between independent clock groups.  The three HDMI clocks remain
# in one synchronous group because PLL2 generates them with fixed ratios.
set_clock_groups -asynchronous \
    -group [get_clocks {pll_60Mhz}] \
    -group [get_clocks {pll_24Mhz}] \
    -group [get_clocks {hdmi_fast_clk hdmi_half_pixel_clk hdmi_pixel_clk}] \
    -group [get_clocks {CSI_PCLK}]
