# Fabric clocks generated by the Interface Designer PLL.
# PLL1 generates exact 96 MHz for control/decoder and 24 MHz for link I/O.

create_clock -period 10.416 -name pll_60Mhz [get_ports {pll_60Mhz}]
create_clock -period 41.667 -name pll_24Mhz [get_ports {pll_24Mhz}]
# PLL2 drives the 1980x750 raster at 50.101 Hz, close to nominal 720p50.
# Keep all three
# periods harmonic so the pixel/half-pixel relationship cannot acquire a
# false 1 ps setup edge from decimal rounding. Values are rounded slightly
# tighter than hardware while preserving exact 2.5x and 5x ratios.
# Physical outputs are 372.0, 148.8, and 74.4 MHz.
create_clock -period 2.688 -name hdmi_fast_clk [get_ports {hdmi_fast_clk}]
create_clock -period 6.720 -name hdmi_half_pixel_clk [get_ports {hdmi_half_pixel_clk}]
create_clock -period 13.440 -name hdmi_pixel_clk [get_ports {hdmi_pixel_clk}]
create_clock -period 10.417 -name CSI_PCLK [get_ports {CSI_PCLK}]

# Control synchronizers and the dual-clock OSD RAM are the intentional
# crossings between independent clock groups.  The three HDMI clocks remain
# in one synchronous group because PLL2 generates them with fixed ratios.
set_clock_groups -asynchronous \
    -group [get_clocks {pll_60Mhz}] \
    -group [get_clocks {pll_24Mhz}] \
    -group [get_clocks {hdmi_fast_clk hdmi_half_pixel_clk hdmi_pixel_clk}] \
    -group [get_clocks {CSI_PCLK}]

# tx_data is a registered diagnostic-SPI response.  tx_index changes only on
# a synchronized SCK rising edge, while tx_data is consumed on the following
# synchronized falling edge, so the response mux has at least two fabric
# cycles by construction.
set_multicycle_path -setup -to {osd_control/tx_data[0]~FF osd_control/tx_data[1]~FF osd_control/tx_data[2]~FF osd_control/tx_data[3]~FF osd_control/tx_data[4]~FF osd_control/tx_data[5]~FF osd_control/tx_data[6]~FF osd_control/tx_data[7]~FF} 2
set_multicycle_path -hold -to {osd_control/tx_data[0]~FF osd_control/tx_data[1]~FF osd_control/tx_data[2]~FF osd_control/tx_data[3]~FF osd_control/tx_data[4]~FF osd_control/tx_data[5]~FF osd_control/tx_data[6]~FF osd_control/tx_data[7]~FF} 1