# Fabric clocks generated by the Interface Designer PLL.
# The PLL physically generates 60 MHz.  Constrain placement to 80 MHz so the
# deployed design retains routing, voltage and temperature margin.
create_clock -period 12.500 -name pll_150Mhz [get_ports {pll_150Mhz}]
create_clock -period 41.667 -name pll_24Mhz [get_ports {pll_24Mhz}]
create_clock -period 10.417 -name CSI_PCLK [get_ports {CSI_PCLK}]

# Pointer synchronizers are the only intentional crossings between these clocks.
set_clock_groups -asynchronous \
    -group [get_clocks {pll_150Mhz}] \
    -group [get_clocks {pll_24Mhz}] \
    -group [get_clocks {CSI_PCLK}]
