# Fabric clocks generated by the Interface Designer PLL.
# The PLL generates 66 MHz for the codec and 24 MHz for the parallel link.
create_clock -period 15.1515 -name pll_60Mhz [get_ports {pll_60Mhz}]
create_clock -period 41.667 -name pll_24Mhz [get_ports {pll_24Mhz}]
create_clock -period 2.688 -name hdmi_fast_clk [get_ports {hdmi_fast_clk}]
create_clock -period 6.720 -name hdmi_half_pixel_clk [get_ports {hdmi_half_pixel_clk}]
create_clock -period 10.417 -name CSI_PCLK [get_ports {CSI_PCLK}]

# Pointer synchronizers are the only intentional crossings between these clocks.
set_clock_groups -asynchronous \
    -group [get_clocks {pll_60Mhz}] \
    -group [get_clocks {pll_24Mhz}] \
    -group [get_clocks {hdmi_fast_clk hdmi_half_pixel_clk}] \
    -group [get_clocks {CSI_PCLK}]
